require ("core.plugins.telescope")
require ("core.plugins.undotree")
require ("core.plugins.fugitive")
require ("core.plugins.lsp")
require ("core.plugins.catppuccin")
require ("core.plugins.42")
require ("core.plugins.presence")
